// 각종 테이블들



//매출
CREATE TABLE  "M_ACCOUNT" 
   (	"NUM" NUMBER(5,0), 
	"PUBLISHER" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER(8,0) NOT NULL ENABLE, 
	"COST" NUMBER(8,0) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(100) NOT NULL ENABLE, 
	"BOOKTYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"REGDATE" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//관리자
CREATE TABLE  "M_ADMIN" 
   (	"SYSNO" VARCHAR2(100) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "M_ADMIN_PK" PRIMARY KEY ("SYSNO") ENABLE
   ) ;
//각종게시판
CREATE TABLE  "M_BOARD" 
   (	"NUM" NUMBER(9,0), 
	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"BOARDTYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(100) NOT NULL ENABLE, 
	"REGDATE" VARCHAR2(100) NOT NULL ENABLE, 
	"RECEIVE" VARCHAR2(100) NOT NULL ENABLE, 
	"GROUPNUM" NUMBER(8,0), 
	"REPLYNUM" NUMBER(5,0), 
	"COUNT" NUMBER(5,0), 
	"BOOKNAME" VARCHAR2(100), 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//등록된 도서
CREATE TABLE  "M_BOOK" 
   (	"NUM" NUMBER(9,0), 
	"BOOKNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(100) NOT NULL ENABLE, 
	"MAINTYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"SUBTYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER(9,0) NOT NULL ENABLE, 
	"IMG" VARCHAR2(100) NOT NULL ENABLE, 
	"PUBLISHER" VARCHAR2(100) NOT NULL ENABLE, 
	"COUNT" NUMBER(9,0) NOT NULL ENABLE, 
	"TOTALSTAR" NUMBER(6,0) NOT NULL ENABLE, 
	"STORY" VARCHAR2(2000) NOT NULL ENABLE, 
	"CONLIST" VARCHAR2(2000) NOT NULL ENABLE, 
	"SAVEDATE" VARCHAR2(1000) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//등록전도서
CREATE TABLE  "M_BOOKREG" 
   (	"NUM" NUMBER(9,0), 
	"BOOKNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"MAINTYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"SUBTYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER(8,0) NOT NULL ENABLE, 
	"IMG" VARCHAR2(100) NOT NULL ENABLE, 
	"PUBLISHER" VARCHAR2(100) NOT NULL ENABLE, 
	"STATE" VARCHAR2(100) NOT NULL ENABLE, 
	"CONLIST" VARCHAR2(1000) NOT NULL ENABLE, 
	"STORY" VARCHAR2(2000) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//장바구니

CREATE TABLE  "M_CART" 
   (	"NUM" NUMBER(8,0), 
	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"IMG" VARCHAR2(100) NOT NULL ENABLE, 
	"BOOKNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PUBLISHER" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER(8,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//결제내역
CREATE TABLE  "M_CASH" 
   (	"NUM" NUMBER(8,0), 
	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"CASHTYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER(8,0) NOT NULL ENABLE, 
	"CASHDATE" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//회원가입통계
CREATE TABLE  "M_JOIN" 
   (	"JOINDATE" VARCHAR2(100) NOT NULL ENABLE, 
	"MAN" NUMBER(9,0) NOT NULL ENABLE, 
	"WOMAN" NUMBER(9,0) NOT NULL ENABLE 
   ) ; 
//로그인db(id중복확인)
CREATE TABLE  "M_LOGIN" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PW" VARCHAR2(50) NOT NULL ENABLE, 
	"LOGTYPE" VARCHAR2(50) NOT NULL ENABLE
   ) ;
//일반회원
CREATE TABLE  "M_MEMBER" 
   (	"NUM" NUMBER(7,0), 
	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"PW" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"BIRTH" VARCHAR2(50) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(50) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"JOINDATE" VARCHAR2(50) NOT NULL ENABLE, 
	"GRADE" VARCHAR2(50), 
	"COMPLAIN" NUMBER(7,0), 
	"CASH" NUMBER(35,0), 
	 PRIMARY KEY ("NUM") ENABLE
   ) ; 
//공지사항
CREATE TABLE  "M_OFFICIAL" 
   (	"NUM" NUMBER(5,0), 
   	"TITLE" VARCHAR2(200) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(100) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(2000) NOT NULL ENABLE, 
	"SAVEDATE" VARCHAR2(2000) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//구매내역
CREATE TABLE  "M_PAYMENT" 
   (	"NUM" NUMBER(8,0), 
	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"IMG" VARCHAR2(100) NOT NULL ENABLE, 
	"BOOKNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PRICE" NUMBER(8,0) NOT NULL ENABLE, 
	"PUBLISHER" VARCHAR2(100) NOT NULL ENABLE, 
	"BUYDATE" VARCHAR2(100) NOT NULL ENABLE, 
	"BOOKMARK" VARCHAR2(200),
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
// 출판사업체
CREATE TABLE  "M_PUB" 
   (	"NUM" NUMBER(10,0), 
	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"PW" VARCHAR2(100) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"LICENSE" NUMBER(10,0) NOT NULL ENABLE, 
	"EMPLOYEE" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(100) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(100) NOT NULL ENABLE, 
	"BANK" VARCHAR2(100) NOT NULL ENABLE, 
	"BANKNUM" NUMBER(10,0) NOT NULL ENABLE, 
	"DEL" NUMBER(3,0), 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//리뷰테이블
CREATE TABLE  "M_REVIEW" 
   (	"NUM" NUMBER(8,0), 
	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"IMG" VARCHAR2(100) NOT NULL ENABLE, 
	"BOOKNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"REVIEW" VARCHAR2(200) NOT NULL ENABLE, 
	"STAR" NUMBER(2,0) NOT NULL ENABLE, 
	"RECOMMEND" NUMBER(6,0) NOT NULL ENABLE, 
	"COMPLAIN" NUMBER(6,0) NOT NULL ENABLE, 
	"REVIEWDATE" VARCHAR2(100) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM") ENABLE
   ) ;
//방문자수통계
CREATE TABLE  "M_VISITOR" 
   (	"VISITDATE" VARCHAR2(100) NOT NULL ENABLE, 
	"COUNT" NUMBER(9,0) NOT NULL ENABLE
   ) ;
//그에 해당하는 시퀀스들

CREATE SEQUENCE   "M_ACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 29 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_ADMIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 24 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 30 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_BOOKREG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 159 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_CART_SEQ"  MIN3VALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_CASH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_MEMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_OFFICIAL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_PAY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_PUB_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE ;
CREATE SEQUENCE   "M_REVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;

 

//초기화
drop table "M_ACCOUNT" purge;
drop sequence "M_ACCOUNT_SEQ";
drop table "M_ADMIN" purge;
drop sequence "M_ADMIN_SEQ";
drop table "M_BOARD" purge;
drop sequence "M_BOARD_SEQ";
drop table "M_BOOK" purge;
drop sequence "M_BOOK_SEQ";
drop table "M_BOOKREG" purge;
drop sequence "M_BOOKREG_SEQ";
drop table "M_CART" purge;
drop sequence "M_CART_SEQ";
drop table "M_JOIN" purge;
drop table "M_CASH" purge;
drop sequence "M_CASH_SEQ";
drop table "M_MEMBER" purge;
drop sequence "M_MEMBER_SEQ";  
drop table "M_CASH" purge;
drop sequence "M_CASH_SEQ";
drop table "M_OFFICIAL" purge;
drop sequence "M_OFFICIAL_SEQ";  
drop table "M_PAYMENT" purge;
drop sequence "M_PAY_SEQ";  
drop table "M_PUB" purge;
drop sequence "M_PUB_SEQ";
drop table "M_REVIEW" purge;
drop sequence "M_REVIEW_SEQ";  
drop table "M_VISITOR" purge;
drop table "M_LOGIN" purge;









